# Generated by Django 6.0.6 on 2026-07-07 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opiniones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta_propuesta', models.CharField(choices=[('RF', 'Requisito Funcional'), ('RNF', 'Requisito No Funcional'), ('Ruido', 'Ruido')], max_length=10, verbose_name='etiqueta propuesta')),
                ('confianza', models.FloatField(blank=True, null=True, verbose_name='confianza')),
                ('metodo', models.CharField(choices=[('zero_shot', 'Zero-shot (similitud a prototipos)'), ('semantico', 'Semántico (Sentence-Transformers)'), ('tfidf', 'TF-IDF (línea base)')], default='zero_shot', max_length=20, verbose_name='método de la propuesta')),
                ('etiqueta_final', models.CharField(blank=True, choices=[('RF', 'Requisito Funcional'), ('RNF', 'Requisito No Funcional'), ('Ruido', 'Ruido')], max_length=10, verbose_name='etiqueta final')),
                ('estado', models.CharField(choices=[('propuesto', 'Propuesto'), ('validado', 'Validado')], default='propuesto', max_length=20, verbose_name='estado')),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de validación')),
                ('notas', models.TextField(blank=True, verbose_name='notas del especialista')),
                ('opinion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requisito', to='opiniones.opinion')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitos_validados', to=settings.AUTH_USER_MODEL, verbose_name='validado por')),
            ],
            options={
                'verbose_name': 'requisito',
                'verbose_name_plural': 'requisitos',
                'ordering': ['estado', '-confianza'],
            },
        ),
    ]
