# Generated by Django 6.0.6 on 2026-08-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisito',
            name='estado',
            field=models.CharField(choices=[('propuesto', 'Propuesto'), ('validado', 'Validado'), ('descartado', 'Descartado')], default='propuesto', max_length=20, verbose_name='estado'),
        ),
    ]
