# Generated by Django 6.0.6 on 2026-06-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorridaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('semantico', 'Semántico (Sentence-Transformers)'), ('tfidf', 'TF-IDF (línea base)')], max_length=20, verbose_name='representación')),
                ('modelo_embeddings', models.CharField(blank=True, help_text='Solo aplica para método semántico.', max_length=200, verbose_name='modelo de embeddings')),
                ('clasificador', models.CharField(choices=[('svm', 'SVM'), ('logreg', 'Regresión Logística'), ('random_forest', 'Random Forest'), ('naive_bayes', 'Naive Bayes'), ('knn', 'K-Nearest Neighbors')], max_length=30, verbose_name='clasificador')),
                ('hiperparametros', models.JSONField(default=dict, verbose_name='hiperparámetros')),
                ('semilla', models.IntegerField(default=42, verbose_name='semilla aleatoria')),
                ('tam_corpus', models.IntegerField(default=0, verbose_name='tamaño del corpus')),
                ('dataset', models.CharField(blank=True, max_length=200, verbose_name='nombre del dataset')),
                ('precision_global', models.FloatField(verbose_name='precisión global')),
                ('recall_global', models.FloatField(verbose_name='recall global')),
                ('f1_global', models.FloatField(verbose_name='F1 global')),
                ('metricas_por_clase', models.JSONField(default=dict, verbose_name='métricas por clase')),
                ('matriz_confusion', models.JSONField(default=list, verbose_name='matriz de confusión')),
                ('notas', models.TextField(blank=True, verbose_name='notas del investigador')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
            ],
            options={
                'verbose_name': 'corrida de evaluación',
                'verbose_name_plural': 'corridas de evaluación',
                'ordering': ['-f1_global'],
            },
        ),
    ]
