# Generated by Django 6.0.6 on 2026-07-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_original', models.TextField(verbose_name='texto original')),
                ('texto_normalizado', models.TextField(blank=True, verbose_name='texto normalizado')),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de publicación')),
                ('calificacion', models.IntegerField(blank=True, null=True, verbose_name='calificación')),
                ('aplicacion', models.CharField(blank=True, max_length=200, verbose_name='aplicación')),
                ('autor_anon', models.CharField(blank=True, max_length=64, verbose_name='autor anónimo')),
                ('fuente', models.CharField(blank=True, max_length=50, verbose_name='fuente')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
            ],
            options={
                'verbose_name': 'opinión',
                'verbose_name_plural': 'opiniones',
                'ordering': ['-fecha_publicacion'],
            },
        ),
    ]
